### ISSUE TITLE
String nofields must not define the URL like this

### ISSUE THREAD

**Issue by mudrd8mz** [moodleuulm/moodle-local_profilecohort#11]
Same problem as in https://github.com/moodleuulm/moodle-local_profiletheme/issues/6

**Comment by mudrd8mz** [comment]
The `$string['nocohorts']` does it correctly.

**Comment by abias** [comment]
Thanks, David, for pointing this out. Once again, I missed this possibility of running Moodle in a subdir.

Fixed in 323be1d6e2f4e9a6b3be29ebb09691c503859957.
