### ISSUE TITLE
compatibility with Moodle 3.3

### ISSUE THREAD

**Issue by Shaomk** [moodleuulm/moodle-local_profilecohort#13]
Great plug-in. Can you check compatibility with Moodle 3.3?

**Comment by abias** [comment]
Hi Shaomk,

it will take a few more weeks until we will start working on 3.3 which makes me very sorry but can't be changed.
Would you please give the 3.2 version a try on 3.3 and report back any issues? Up to now we haven't received any problem reports with 3.3, so I am quite confident that it should work.

Thanks,
Alex

**Comment by Shaomk** [comment]
Hi, yes the plugin works fine. Thank you so much.

**Comment by abias** [comment]
Great to hear that, thanks!
