### ISSUE TITLE
Add 2 conditions to a rule

### ISSUE THREAD

**Issue by ecampbell** [moodleuulm/moodle-local_profilecohort#15]
I tried this plugin out on Moodle 3.1 so I'm not sure if it worked as intended. I would like to be able to set 2 conditions before a user is added to a cohort, such as "Custom Profile Field 1 is set to X" AND "Custom Profile Field 2 is set to Y". Is this possible?
A good example of what I mean is in the Enrol Attributes plugin at https://moodle.org/plugins/enrol_attributes

**Comment by ecampbell** [comment]
To answer my own question, you can add 2 conditions in 3.4

**Comment by abias** [comment]
Eoin, I'm happy that you could help yourself.
