### ISSUE TITLE
No Default values

### ISSUE THREAD

**Issue by cerveos24** [moodleuulm/moodle-local_profilecohort#20]
This plugin seems to be what we need, and its by far one of the best written plugins I've seen, kudos to you guys!

I just that can't pass the error "**No custom user profile fields have been defined.
You need to define custom user profile fields before you can add rules here - please visit User profile fields to create at least one custom user profile field**"  even though I created custom fields.

There is a similar case already, but the resolution does not seems to be the same for my case..

Thanks in advance for any support.

**Comment by cerveos24** [comment]
**UPDATE!**.  Weird but I rebooted the server and the error is gone... I will now continue learning how to use it.  **The server is Windows2016, PHP7.2, IIS10 and Moodle 3.6.2 if that matters.**
  THANKS

**Comment by cerveos24** [comment]
NEver mind...The error is gone, but I can't see the custom values, only if I do the text, but I want to use date to force the cohort to assign new users by date of hire.

**Comment by abias** [comment]
Hi @cerveos24 ,

I don't completely understand your problem.
Can you please provide detailed steps to reproduce the problem on a fresh Moodle installation so that I reproduce it here, too?

Thanks,
Alex

**Comment by cerveos24** [comment]
Alex,

I am sorry for not being clear.  Basically, my problem is that only the checkboxes and text functionality are actually working.  If I am to create a new custom profile, I get the error stated in the original case.  But you know what, the checkboxes will work fine for me, because I can configure there whtn I need in a very simple way.  So, let's close the case and if you see anything that can help me, just email me to the account on file.  If not, well, the plugin is great, good job and thank you!
