### ISSUE TITLE
Compatability with Conditional Fields plugin

### ISSUE THREAD

**Issue by ghost** [moodleuulm/moodle-local_profilecohort#28]
When you add a new custom [Conditional Field](https://moodle.org/plugins/profilefield_conditional) to the moodle user profile, the new field does not display in the 'Add rule for customer profile field...' dropdown.

**Comment by abias** [comment]
As the issue creater's Github account was deleted and as the reasons for this problem is most probably to be searched in the conditional field plugin and not in this plugin, I am closing this issue.
