### ISSUE TITLE
page load time

### ISSUE THREAD

**Issue by martinvivek** [moodleuulm/moodle-local_profilecohort#4]
we have around 80 rule. while we open the profile field based cohort it takes around an hour to open the page. to add another two rule it takes 2.5 hours. i am enclosing the  database details of the plugin. 
We use windows 2008 IIS
moodle 3.2.2+
php 7.0.3

note: it may not by you plugin may be but whenever i open the page server hits 100% utilization and java is the highest load it takes.

[cohort relation.xlsx](https://github.com/moodleuulm/moodle-local_profilecohort/files/852105/cohort.relation.xlsx)

**Comment by abias** [comment]
Hi martinvivek,

thanks for your report.

Before we dive into analysis please answer these questions:
* In #3 , you asked about settings of the plugin and told me that you changed something manually. Are you sure you reverted everything you changed in the database?
* You said "and java is the highest load it takes." What java load do you mean - do you mean javascript in the browser?

Thanks,
Alex

**Comment by martinvivek** [comment]
No in #3, as you said whenever the rule is added it performing the cron job. so it not have any issues,
we added the event observer instead of user_loggedin we made it to user_updated only. we reverted everything in database.

but when i adding the rules the page not loading that much easily, it takes more than 2 hours at the same time the server load is increasing. 

when we raise the complaint to our it dept. they said what javascript you using in the website may triggering the load ( that time we adding the rules ) by that only i said Now there is no load in server it performing very well.

i dont know really this plugin is the problem. whatever script using may cause only in client side not in the server side that i know. just for clarity i asked you. Sorry if i may wrong. you plugin make our job less even it takes 2 hours it is a one time job. thanks for your plugin


and one thing we noted when we adding rules before adding  another rule and joining, the cronjob is started running, it started working in uncompleted rule.

**Comment by abias** [comment]
Hi martinvivek,

today, we release the first final version of the plugin. As your problem report is somehow vague up to now, I would like to ask you to do another test with the latest version and to give me steps to reproduce the problem on a clean Moodle installation.

Thanks,
Alex

**Comment by martinvivek** [comment]
I cannot reproduced the same. we are running it on production server. initially we assigned everything (almost 300 rules) that time only i have a page load issue. once we assigned everything was fine and i updated with latest one also.

Thanks for your support. you can close this issue

**Comment by abias** [comment]
All right, thanks for your response.
